---
- hosts: all
  
  vars:
    homebrew_clear_cache: true

    homebrew_installed_packages:
      - ssh-copy-id
      - caskroom/cask/brew-cask
      - virtualbox
      - google-chrome
    
    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.homebrew
