---
- hosts: all
  
  vars:
    homebrew_clear_cache: true
    homebrew_prefix: /opt/homebrew
    homebrew_install_path: "{{ homebrew_prefix }}"

    homebrew_installed_packages:
      - ssh-copy-id
      - virtualbox
      - google-chrome
    
    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.homebrew
