---
- hosts: all
  become: true
  
  vars:
    homebrew_prefix: /opt/homebrew
    homebrew_install_path: "{{ homebrew_prefix }}"

  roles:
    - role: geerlingguy.homebrew
    - role: elliotweiser.osx-command-line-tools
