---
- hosts: apple_arm64 

  vars:
    homebrew_prefix: /opt/homebrew
    homebrew_install_path: "{{ homebrew_prefix }}"
    homebrew_upgrade_all_packages: yes

    homebrew_taps:
      - homebrew/core
      - homebrew/cask

    homebrew_uninstalled_packages: []

    homebrew_installed_packages:
      - awscli
      - bpytop
      - bmon
      - curl
      - git
      - go
      - gpg2
      - helm
      - jq
      - htop
      - maven 
      - minikube
      - mtr
      - ncdu
      - nmap
      - pinentry
      - pwgen
      - ssh-copy-id
      - telnet
      - terraform
      - tmux
      - tree
      - unzip
      - vim
      - virtualenv
      - watch
      - wget

    homebrew_cask_apps:
#      - docker -- Apple Silicon M1 not in brew at devleopment time
      - eclipse-installer
      - google-chrome
#      - virtualbox
#      - virtualbox-extension-pack
      - vlc

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.homebrew

