---
- hosts: all
  become: true
  
  vars:
    homebrew_clear_cache: true

    homebrew_installed_packages:
      - ssh-copy-id

    homebrew_cask_apps:
      - virtualbox
      - google-chrome
      
    homebrew_taps: []

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.homebrew
