---
- hosts: all

  vars:
    homebrew_upgrade_all_packages: yes
    
    homebrew_taps:
      - homebrew/core
      - homebrew/cask

    homebrew_uninstalled_packages: []
    
    homebrew_installed_packages:
      - ssh-copy-id
      - virtualbox
      - google-chrome
    
  roles:
    - role: elliotweiser.osx-command-line-tools

  tasks:
    # Tap.
    - name: Ensure configured taps are tapped.
      homebrew_tap:
        tap: '{{ item.name | default(item) }}'
        url: '{{ item.url | default(omit) }}'
        state: present
      loop: "{{ homebrew_taps }}"

    # Brew.
    - name: Ensure blacklisted homebrew packages are not installed.
      homebrew: 
        name: "{{ item }}" 
        state: absent
      loop: "{{ homebrew_uninstalled_packages }}"

    - name: Ensure configured homebrew packages are installed.
      homebrew:
        name: "{{ item.name | default(item) }}"
        install_options: "{{ item.install_options | default(omit) }}"
        state: present
      loop: "{{ homebrew_installed_packages }}"

    - name: Upgrade all homebrew packages (if configured).
      homebrew: 
        update_homebrew: yes 
        upgrade_all: yes
      when: homebrew_upgrade_all_packages
